# Generated by Django 2.2.2 on 2019-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190608_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(to='main.OtusUser'),
        ),
    ]
