# Generated by Django 2.2.2 on 2019-09-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_otususer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='otususer',
            name='date_of_brith',
            field=models.DateField(blank=True, null=True),
        ),
    ]
