# Generated by Django 2.2.2 on 2019-09-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_otususer_date_of_brith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
