# Generated by Django 2.2.2 on 2019-06-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190608_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otususer',
            name='courses',
        ),
    ]
